+incdir+../design
+incdir+../verif
+incdir+../verif/alu_sequences
+incdir+../verif/alu_sequences
+incdir+../verif/tests
../design/alu.sv
../verif/alu_interface.sv
../verif/alu_pkg.sv
../verif/alu_tb_top.sv